[[statics]]
  # The source directory for your build output (change this to match your build setup)
  source = "build"

  # The directory in the published static site where your index.html file is located
  # This depends on your build setup; it may be the root directory or a different one
  dest = "/"

  # Add a list of rewrites for single-page applications
  [[statics.rewrites]]
    sourcePath = "/<^((?!\\.).)*$>"
    # Replace with the path to your main HTML file
    destination = "/index.html"
